import { describe, expectTypeOf, test } from 'vitest';
import type { StarlightUserConfig } from '../../utils/user-config';

describe('sidebar', () => {
	type SidebarUserItem = NonNullable<StarlightUserConfig['sidebar']>[number];

	test('emits a type error for custom attributes on groups', () => {
		// Links
		expectTypeOf('getting-started').toExtend<SidebarUserItem>();
		expectTypeOf({ slug: 'getting-started' }).toExtend<SidebarUserItem>();
		expectTypeOf({
			label: 'Getting Started',
			link: '/getting-started/',
		}).toExtend<SidebarUserItem>();

		// Groups
		expectTypeOf({
			label: 'References',
			items: [],
		}).toExtend<SidebarUserItem>();

		// Links with attributes
		expectTypeOf({
			slug: 'getting-started',
			attrs: { class: 'test' },
		}).toExtend<SidebarUserItem>();
		expectTypeOf({
			label: 'Getting Started',
			link: '/getting-started/',
			attrs: { class: 'test' },
		}).toExtend<SidebarUserItem>();

		// Groups with attributes which are not supported
		expectTypeOf({
			label: 'References',
			items: [],
			attrs: { class: 'test' },
			// @ts-expect-error - Attributes are not supported on groups
		}).toExtend<SidebarUserItem>();
	});

	test('emits a type error for autogenerated groups', () => {
		// Groups with autogenerated items
		expectTypeOf({
			label: 'References',
			items: [{ autogenerate: { directory: 'references' } }],
		}).toExtend<SidebarUserItem>();

		// Autogenerated groups are no longer supported
		expectTypeOf({
			label: 'References',
			autogenerate: { directory: 'references' },
			// @ts-expect-error - Autogenerated groups are no longer supported
		}).toExtend<SidebarUserItem>();
	});
});
