import { expect, test, vi } from 'vitest';
import { flattenSidebar, getSidebar } from '../../utils/navigation';

vi.mock('astro:content', async () =>
	(await import('../test-utils')).mockedAstroContent({
		docs: [
      ['environmental-impact.md', { title: 'fourth' }],
			['guides/authoring-content.md', { title: 'fifth' }],
			['index.mdx', { title: 'first' }],
			['reference/frontmatter.md', { title: 'seventh' }],
			['guides/components.mdx', { title: 'sixth' }],
			// @ts-expect-error — Using a slug not present in Starlight docs site
			['bar/baz.mdx', { title: 'second' }],
      // @ts-expect-error — Using a slug not present in Starlight docs site
			['bar/zoo.mdx', { title: 'third' }],
		],
	})
);

test('autogenerated sidebar is sorted alphabetically by filename', () => {
	const sidebar = getSidebar('/', undefined);
	const flattened = flattenSidebar(sidebar);

	expect(flattened.map((e) => e.label)).toMatchInlineSnapshot(`
		[
		  "first",
		  "second",
		  "third",
		  "fourth",
		  "fifth",
		  "sixth",
		  "seventh",
		]
	`);
});
