body:
  - type: markdown
    attributes:
      value: |
        Thank you for getting in touch! Please fill out this form as completely as possible.

        Want to report a problem with the Starlight docs? [Open a new issue](https://github.com/withastro/starlight/issues/new?assignees=&labels=&projects=&template=---02-docs-issue.yml)
        Want to chat before posting? [Join us in the `#starlight` channel on Discord](https://astro.build/chat)
  - type: textarea
    id: summary
    attributes:
      label: What is your idea?
      description: A brief, one or two sentence description of your idea for how to improve the Starlight docs.
    validations:
      required: true
  - type: textarea
    id: background
    attributes:
      label: Why is this important?
      description: Explain why this idea is valuable. What problems would it solve? Which users would it help?
    validations:
      required: true
  - type: textarea
    id: prior-art
    attributes:
      label: How does your idea relate to existing docs content?
      description: Are there specific pages you would like to change? Or existing pages that are related to your proposal?
      placeholder: |
        - Example
        - Example
        - Example
  - type: checkboxes
    id: will-pr
    attributes:
      label: Participation
      description: Let us know if your interested in contributing this feature yourself.
      options:
        - label: I am willing to submit a pull request for this feature.
          required: false
