import { z } from 'astro/zod';
import type { SchemaContext } from 'astro:content';
import { HeadConfigSchema } from './schemas/head';
import { PrevNextLinkConfigSchema } from './schemas/prevNextLink';
import { FrontmatterTableOfContentsSchema } from './schemas/tableOfContents';
import { BadgeConfigSchema } from './schemas/badge';
import { HeroSchema } from './schemas/hero';
import { SidebarLinkItemHTMLAttributesSchema } from './schemas/sidebar';
export { i18nSchema } from './schemas/i18n';

/** Default content collection schema for Starlight’s `docs` collection. */
const StarlightFrontmatterSchema = (context: SchemaContext) =>
	z.object({
		/** The title of the current page. Required. */
		title: z.string(),

		/**
		 * A short description of the current page’s content. Optional, but recommended.
		 * A good description is 150–160 characters long and outlines the key content
		 * of the page in a clear and engaging way.
		 */
		description: z.string().optional(),

		/**
		 * Custom URL where a reader can edit this page.
		 * Overrides the `editLink.baseUrl` global config if set.
		 *
		 * Can also be set to `false` to disable showing an edit link on this page.
		 */
		editUrl: z.union([z.url(), z.boolean()]).optional().default(true),

		/** Set custom `<head>` tags just for this page. */
		head: HeadConfigSchema({ source: 'content' }),

		/** Override global table of contents configuration for this page. */
		tableOfContents: FrontmatterTableOfContentsSchema(),

		/**
		 * Set the layout style for this page.
		 * Can be `'doc'` (the default) or `'splash'` for a wider layout without any sidebars.
		 */
		template: z.enum(['doc', 'splash']).default('doc'),

		/** Display a hero section on this page. */
		hero: HeroSchema(context).optional(),

		/**
		 * The last update date of the current page.
		 * Overrides the `lastUpdated` global config or the date generated from the Git history.
		 */
		lastUpdated: z.union([z.date(), z.boolean()]).optional(),

		/**
		 * The previous navigation link configuration.
		 * Overrides the `pagination` global config or the link text and/or URL.
		 */
		prev: PrevNextLinkConfigSchema(),
		/**
		 * The next navigation link configuration.
		 * Overrides the `pagination` global config or the link text and/or URL.
		 */
		next: PrevNextLinkConfigSchema(),

		sidebar: z
			.object({
				/**
				 * The order of this page in the navigation.
				 * Pages are sorted by this value in ascending order. Then by slug.
				 * If not provided, pages will be sorted alphabetically by slug.
				 * If two pages have the same order value, they will be sorted alphabetically by slug.
				 */
				order: z.number().optional(),

				/**
				 * The label for this page in the navigation.
				 * Defaults to the page `title` if not set.
				 */
				label: z.string().optional(),

				/**
				 * Prevents this page from being included in autogenerated sidebar groups.
				 */
				hidden: z.boolean().default(false),
				/**
				 * Adds a badge to the sidebar link.
				 * Can be a string or an object with a variant and text.
				 * Variants include 'note', 'tip', 'caution', 'danger', 'success', and 'default'.
				 * Passing only a string defaults to the 'default' variant which uses the site accent color.
				 */
				badge: BadgeConfigSchema(),
				/** HTML attributes to add to the sidebar link. */
				attrs: SidebarLinkItemHTMLAttributesSchema(),
			})
			.prefault({}),

		/** Display an announcement banner at the top of this page. */
		banner: z
			.object({
				/** The content of the banner. Supports HTML syntax. */
				content: z.string(),
			})
			.optional(),

		/** Pagefind indexing for this page - set to false to disable. */
		pagefind: z.boolean().default(true),

		/**
		 * Indicates that this page is a draft and will not be included in production builds.
		 * Note that the page will still be available when running Astro in development mode.
		 */
		draft: z.boolean().default(false),
	});
/** Type of Starlight’s default frontmatter schema. */
type DefaultSchema = ReturnType<typeof StarlightFrontmatterSchema>;

/** Base subset of Zod types that we support passing to the `extend` option. */
type BaseSchema<T extends z.ZodRawShape = z.ZodRawShape> = z.ZodObject<T>;

/** Type that extends Starlight’s default schema with an optional, user-defined schema. */
type ExtendedSchema<T extends BaseSchema = never> = [T] extends [never]
	? DefaultSchema
	: MergedSchema<DefaultSchema, T>;

/** Type-level equivalent of {@link mergeWithDefaultSchema}. */
type MergedSchema<Default extends z.core.$ZodType, User extends z.core.$ZodType> =
	User extends z.ZodOptional<infer WrappedSchema extends z.core.$ZodType>
		? z.ZodOptional<MergedSchema<UnwrappedSchema<Default>, WrappedSchema>>
		: User extends z.ZodNullable<infer WrappedSchema extends z.core.$ZodType>
			? z.ZodNullable<MergedSchema<UnwrappedSchema<Default>, WrappedSchema>>
			: User extends z.ZodDefault<infer WrappedSchema extends z.core.$ZodType>
				? z.ZodDefault<MergedSchema<UnwrappedSchema<Default>, WrappedSchema>>
				: User extends z.ZodPrefault<infer WrappedSchema extends z.core.$ZodType>
					? z.ZodPrefault<MergedSchema<UnwrappedSchema<Default>, WrappedSchema>>
					: UnwrappedSchema<Default> extends z.ZodObject<infer DefaultShape>
						? User extends z.ZodObject<infer UserShape, infer UserConfig>
							? z.ZodObject<MergedShape<DefaultShape, UserShape>, UserConfig>
							: User
						: UnwrappedSchema<Default> extends z.ZodArray<
									infer DefaultItemSchema extends z.core.$ZodType
							  >
							? User extends z.ZodArray<infer UserItemSchema extends z.core.$ZodType>
								? z.ZodArray<MergedSchema<DefaultItemSchema, UserItemSchema>>
								: User
							: User;

/** Type-level equivalent of {@link unwrapSchema}. */
type UnwrappedSchema<T extends z.core.$ZodType> =
	T extends z.ZodOptional<infer Wrapped extends z.core.$ZodType>
		? UnwrappedSchema<Wrapped>
		: T extends z.ZodNullable<infer Wrapped extends z.core.$ZodType>
			? UnwrappedSchema<Wrapped>
			: T extends z.ZodDefault<infer Wrapped extends z.core.$ZodType>
				? UnwrappedSchema<Wrapped>
				: T extends z.ZodPrefault<infer Wrapped extends z.core.$ZodType>
					? UnwrappedSchema<Wrapped>
					: T;

/**
 * Merged Zod object shapes, preserving default properties, adding user-only properties, and
 * recursively merging shared properties.
 */
type MergedShape<Default extends z.ZodRawShape, User extends z.ZodRawShape> = {
	[Key in keyof Default | keyof User]: Key extends keyof User
		? Key extends keyof Default
			? MergedSchema<Default[Key], User[Key]>
			: User[Key]
		: Key extends keyof Default
			? Default[Key]
			: never;
};

interface DocsSchemaOpts<T extends BaseSchema> {
	/**
	 * Extend Starlight’s schema with additional fields.
	 *
	 * @example
	 * // Extend the built-in schema with a Zod schema.
	 * docsSchema({
	 * 	extend: z.object({
	 * 		// Add a new field to the schema.
	 * 		category: z.enum(['tutorial', 'guide', 'reference']).optional(),
	 * 	}),
	 * })
	 *
	 * // Use the Astro image helper.
	 * docsSchema({
	 * 	extend: ({ image }) => {
	 * 		return z.object({
	 * 			cover: image(),
	 * 		});
	 * 	},
	 * })
	 */
	extend?: T | ((context: SchemaContext) => T);
}

/** Content collection schema for Starlight’s `docs` collection. */
export function docsSchema<T extends BaseSchema = never>(
	...args: [DocsSchemaOpts<T>?]
): (context: SchemaContext) => ExtendedSchema<T> {
	const [options = {}] = args;
	const { extend } = options;

	return (context: SchemaContext) => {
		const UserSchema = typeof extend === 'function' ? extend(context) : extend;

		return (
			UserSchema
				? mergeWithDefaultSchema(StarlightFrontmatterSchema(context), UserSchema)
				: StarlightFrontmatterSchema(context)
		) as ExtendedSchema<T>;
	};
}

function mergeWithDefaultSchema(defaultSchema: z.ZodType, userSchema: z.ZodType): z.ZodType {
	const unwrappedDefaultSchema = unwrapSchema(defaultSchema);

	if (isWrappedSchema(userSchema)) {
		return userSchema.clone({
			...userSchema._zod.def,
			innerType: mergeWithDefaultSchema(unwrappedDefaultSchema, userSchema._zod.def.innerType),
		} as Parameters<typeof userSchema.clone>[0]);
	}

	if (isZodObject(unwrappedDefaultSchema) && isZodObject(userSchema)) {
		const shape: z.core.$ZodLooseShape = { ...unwrappedDefaultSchema.shape };

		for (const key of Object.keys(userSchema.shape)) {
			const userFieldSchema = userSchema.shape[key] as z.ZodType;
			const defaultFieldSchema = shape[key] as z.ZodType | undefined;

			shape[key] = defaultFieldSchema
				? mergeWithDefaultSchema(defaultFieldSchema, userFieldSchema)
				: userFieldSchema;
		}

		return userSchema.safeExtend(shape);
	}

	if (isZodArray(unwrappedDefaultSchema) && isZodArray(userSchema)) {
		return userSchema.clone({
			...userSchema._zod.def,
			element: mergeWithDefaultSchema(unwrappedDefaultSchema.element, userSchema.element),
		});
	}

	return userSchema;
}

/**
 * Unwrap any Zod schema that wraps other schemas, such as `z.optional()`, `z.nullable()`,
 * `z.default()`, etc. until we reach the innermost schema.
 */
function unwrapSchema(schema: z.ZodType): z.ZodType {
	let current = schema;

	while (isWrappedSchema(current)) {
		current = current._zod.def.innerType;
	}

	return current;
}

/**
 * Check if a schema wraps another schema which can happen when using modifiers like
 * `z.optional()`, `z.nullable()`, `z.default()`, etc.
 */
function isWrappedSchema(schema: z.ZodType): schema is z.ZodType & {
	_zod: { def: z.ZodType['_zod']['def'] & { innerType: z.ZodType } };
} {
	return (
		schema._zod.def.type === 'optional' ||
		schema._zod.def.type === 'nullable' ||
		schema._zod.def.type === 'default' ||
		schema._zod.def.type === 'prefault'
	);
}

function isZodObject(schema: z.ZodType): schema is z.ZodObject<z.ZodRawShape> {
	return schema._zod.def.type === 'object';
}

function isZodArray(schema: z.ZodType): schema is z.ZodArray<z.ZodType> {
	return schema._zod.def.type === 'array';
}
