import { z } from 'astro/zod';
import type { SchemaContext, ContentConfig } from 'astro:content';
import config from 'virtual:starlight/user-config';
import { collections } from 'virtual:starlight/collection-config';
import { stripLeadingAndTrailingSlashes } from './path';
import { getToC, type PageProps, type StarlightRouteData } from './route-data';
import type { StarlightDocsEntry } from './routing';
import { slugToLocaleData } from './slugs';
import { getPrevNextLinks, getSidebar } from './navigation';
import { useTranslations } from './translations';

/**
 * The frontmatter schema for virtual pages derived from the default schema for Starlight’s `docs`
 * content collection.
 * The frontmatter schema for virtual pages cannot include some properties which will be omitted
 * and some others needs to be refined to a stricter type.
 */
const StarlightVirtualFrontmatterSchema = (context: SchemaContext) => {
	// We manually cast the schema to its own type directly imported from `astro:content` even though
	// the virtual module definition is using this same type otherwise the type will fail to be
	// resolved by consumers and fall back to `any`.
	const docsSchema = (collections.docs.schema as ContentConfig['collections']['docs']['schema'])!;
	const schema = typeof docsSchema === 'function' ? docsSchema(context) : docsSchema;

	return schema.transform((frontmatter) => {
		/**
		 * Virtual pages can only be edited if an edit URL is explicitly provided.
		 * The `sidebar` frontmatter prop only works for pages in an autogenerated links group.
		 * Virtual page links cannot be autogenerated.
		 *
		 * These changes to the schema are done using a transformer and not using the usual `omit`
		 * method because when the frontmatter schema is extended by the user, an intersection between
		 * the default schema and the user schema is created using the `and` method. Intersections in
		 * Zod returns a `ZodIntersection` object which does not have some methods like `omit` or
		 * `pick`.
		 *
		 * This transformer only sets the `editUrl` default value and removes the `sidebar` property
		 * from the validated output but does not appply any changes to the input schema type itself so
		 * this needs to be done manually.
		 *
		 * @see StarlightVirtualFrontmatter
		 * @see https://github.com/colinhacks/zod#intersections
		 */
		const { editUrl, sidebar, ...others } = frontmatter;
		const virtualEditUrl = editUrl === undefined || editUrl === true ? false : editUrl;
		return { ...others, editUrl: virtualEditUrl };
	});
};

/**
 * Type of Starlight’s virtual frontmatter schema.
 * We manually refines the `editUrl` type and omit the `sidebar` property as it's not possible to
 * do that on the schema itself using Zod but the proper validation is still using a transformer.
 * @see StarlightVirtualFrontmatterSchema
 */
type StarlightVirtualFrontmatter = Omit<
	z.input<ReturnType<typeof StarlightVirtualFrontmatterSchema>>,
	'editUrl' | 'sidebar'
> & { editUrl?: string | false };

/**
 * The props accepted by the `<VirtualPage/>` component.
 */
export type VirtualPageProps = Prettify<
	// Remove the index signature from `Route`, omit undesired properties and make the rest optional.
	Partial<Omit<RemoveIndexSignature<PageProps>, 'entry' | 'entryMeta' | 'id' | 'locale' | 'slug'>> &
		// Add back the mandatory slug property.
		Pick<PageProps, 'slug'> &
		// Add the sidebar definitions for a virtual page.
		Partial<Pick<StarlightRouteData, 'hasSidebar' | 'sidebar'>> & {
			// And finally add the virtual frontmatter properties in a `frontmatter` property.
			frontmatter: StarlightVirtualFrontmatter;
		}
>;

/**
 * A docs entry used for virtual pages meant to be rendered by plugins and which is safe to cast
 * to a `StarlightDocsEntry`.
 * A virtual docs entry cannot be rendered like a content collection entry.
 */
type VirtualDocsEntry = Omit<StarlightDocsEntry, 'id' | 'render'> & {
	/**
	 * The unique ID for this virtual page which cannot be inferred from codegen like content
	 * collection entries.
	 */
	id: string;
};

export function generateVirtualRouteData({
	props,
	url,
}: {
	props: VirtualPageProps;
	url: URL;
}): StarlightRouteData {
	const { isFallback, frontmatter, slug, ...routeProps } = props;
	const virtualFrontmatter = getVirtualFrontmatter(frontmatter);
	const id = `${stripLeadingAndTrailingSlashes(slug)}.md`;
	const localeData = slugToLocaleData(slug);
	const sidebar = props.sidebar ?? getSidebar(url.pathname, localeData.locale);
	const headings = props.headings ?? [];
	const virtualEntry: VirtualDocsEntry = {
		id,
		slug,
		body: '',
		collection: 'docs',
		data: {
			...virtualFrontmatter,
			sidebar: {
				attrs: {},
				hidden: false,
			},
		},
	};
	const entry = virtualEntry as StarlightDocsEntry;
	const entryMeta: StarlightRouteData['entryMeta'] = {
		dir: props.dir ?? localeData.dir,
		lang: props.lang ?? localeData.lang,
		locale: localeData.locale,
	};
	const editUrl = virtualFrontmatter.editUrl ? new URL(virtualFrontmatter.editUrl) : undefined;
	const lastUpdated =
		virtualFrontmatter.lastUpdated instanceof Date ? virtualFrontmatter.lastUpdated : undefined;
	const routeData: StarlightRouteData = {
		...routeProps,
		...localeData,
		id,
		editUrl,
		entry,
		entryMeta,
		hasSidebar: props.hasSidebar ?? entry.data.template !== 'splash',
		headings,
		labels: useTranslations(localeData.locale).all(),
		lastUpdated,
		pagination: getPrevNextLinks(sidebar, config.pagination, entry.data),
		sidebar,
		slug,
		toc: getToC({
			...routeProps,
			...localeData,
			entry,
			entryMeta,
			headings,
			id,
			locale: localeData.locale,
			slug,
		}),
	};
	if (isFallback) {
		routeData.isFallback = true;
	}
	return routeData;
}

/** Validates the virtual frontmatter properties from the props received by a virtual page. */
function getVirtualFrontmatter(frontmatter: StarlightVirtualFrontmatter) {
	// This needs to be in sync with ImageMetadata.
	// https://github.com/withastro/astro/blob/cf993bc263b58502096f00d383266cd179f331af/packages/astro/src/assets/types.ts#L32
	return StarlightVirtualFrontmatterSchema({
		image: () =>
			z.object({
				src: z.string(),
				width: z.number(),
				height: z.number(),
				format: z.union([
					z.literal('png'),
					z.literal('jpg'),
					z.literal('jpeg'),
					z.literal('tiff'),
					z.literal('webp'),
					z.literal('gif'),
					z.literal('svg'),
					z.literal('avif'),
				]),
			}),
	}).parse(frontmatter);
}

// https://stackoverflow.com/a/66252656/1945960
type RemoveIndexSignature<TType> = {
	[Tkey in keyof TType as string extends Tkey
		? never
		: number extends Tkey
		? never
		: symbol extends Tkey
		? never
		: Tkey]: TType[Tkey];
};

// https://www.totaltypescript.com/concepts/the-prettify-helper
type Prettify<TType> = {
	[TKey in keyof TType]: TType[TKey];
} & {};
