import { defineVitestConfig } from '../test-config';

export default defineVitestConfig({
	title: 'Sidebar Autogenerated Collapsed Test',
	sidebar: [
		{
			label: 'Reference (group: default - autogenerated: default)',
			items: [{ autogenerate: { directory: 'reference' } }],
		},
		{
			label: 'Reference (group: not collapsed - autogenerated: default)',
			collapsed: false,
			items: [{ autogenerate: { directory: 'reference' } }],
		},
		{
			label: 'Reference (group: collapsed - autogenerated: default)',
			collapsed: true,
			items: [{ autogenerate: { directory: 'reference' } }],
		},
		{
			label: 'Reference (group: default - autogenerated: collapsed)',
			items: [{ autogenerate: { directory: 'reference', collapsed: true } }],
		},
		{
			label: 'Reference (group: not collapsed - autogenerated: collapsed)',
			collapsed: false,
			items: [{ autogenerate: { directory: 'reference', collapsed: true } }],
		},
		{
			label: 'Reference (group: collapsed - autogenerated: not collapsed)',
			collapsed: true,
			items: [{ autogenerate: { directory: 'reference', collapsed: false } }],
		},
	],
});
