name: File icons generator

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  icons:
    name: Generate file icons
    if: github.repository_owner == 'withastro'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # open the automated pull request with `gh pr create`
    steps:
      - name: Checkout Repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup PNPM
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24.18.0
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i

      - name: Run file icons generator
        run: pnpm build
        working-directory: packages/file-icons-generator

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.FREDKBOT_GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git checkout -b ci/file-icons
          git add .
          if git commit -m 'ci: update file icons'; then
            git push -u origin ci/file-icons --force
            gh pr view ci/file-icons || gh pr create --title 'ci: update file icons' --body 'This PR is auto-generated by a GitHub action to update the file icons and file tree definitions available in Starlight.' --head ci/file-icons
          fi
