name: Format

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    if: github.repository_owner == 'withastro'
    uses: withastro/automation/.github/workflows/format.yml@c8a2e8bcf0a6c007770d30ba0c18effc33e05e7f # main
    with:
      command: "format"
    secrets: inherit
