name: Format

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  format:
    if: github.repository_owner == 'withastro'
    uses: withastro/automation/.github/workflows/format.yml@cd27ae3c8076e195a4f0311c18967b12ade6f3b4 # main
    with:
      command: "format"
    secrets: inherit
